# Generated by Django 4.2.1 on 2023-05-22 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userfollows_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followed_user', through='authentication.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
