# Generated by Django 4.2.1 on 2023-05-22 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, through='authentication.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
